config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'users#index'
  resources :users, only: [:index, :show, :destroy, :edit, :update] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # api routes

  namespace :api do
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }
  after_initialize :set_default_photo

  def set_default_photo
    self.photo ||= ActionController::Base.helpers.asset_path('avatars/13.png') if photo.blank?
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  private

  # If you have extra params to permit, append them to the sanitizer.
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    if params[:id] == 'sign_out'
      sign_out current_user
      redirect_to root_path and return
    end

    @user = User.find(params[:id])
    @posts = @user.posts.includes(:comments)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.posts.each do |post|
      post.comments.destroy_all
      post.likes.destroy_all
    end
    @user.posts.destroy_all
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :photo)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render partial: 'users/shared/header' %>
<div class="flex flex-col p-4 pt-32 bg-slate-400 min-h-screen">
  <div class="bg-white p-4 mt-8 rounded-lg flex flex-col shadow-lg shadow-indigo-500/40 max-w-lg m-auto mt-3">
    <div class="flex items-center justify-around w-full">
      <h2 class="font-bold">Edit Your Profile</h2>
      <span class="font-bold">|</span>
      <% if user_signed_in? && current_user == @user %>
      <%= button_to "Delete My Account", @user, method: :delete, data: { confirm: "Are you sure?" }, class: 'font-bold' %>
      <% end %>
    </div>

    <%= form_with(model: @user, url: user_path(@user), method: :patch, class: 'm-4 flex flex-col gap-2' ) do |form| %>
      <div class="mb-4">
        <%= form.label :name, class: 'block text-gray-700 font-bold mb-2' %>
        <%= form.text_field :name, class: 'border-indigo-500/100 w-full rounded-lg' %>
      </div>

      <div class="mb-4">
        <%= form.label :bio, class: 'block text-gray-700 font-bold mb-2' %>
        <%= form.text_area :bio, class: 'border-indigo-500/100 w-full rounded-lg' %>
      </div>

      <div class="mb-4">
        <%= form.label :photo, class: 'block text-gray-700 font-bold mb-2' %>
        <%= form.file_field :photo, class: 'form-input border-indigo-500/100 w-full rounded-lg' %>
      </div>

      <div class="flex items-center justify-around">
        <%= form.submit "Update", class: 'bg-slate-600 hover:bg-slate-700 text-white p-2 rounded-lg font-bold'%>
        <%= link_to "Cancel", user_path(@user), class: 'bg-slate-600 hover:bg-slate-700 text-white p-2 rounded-lg font-bold' %>
      </div>
    <% end %>

  </div> 
  <%= link_to user_path(current_user), class: 'm-auto mt-4' do %>
    <%= image_tag("icons/back", alt: "Back icon", width: 35, height: 35) %>
  <% end %>

</div>
<%= render partial: 'users/shared/footer' %>

app/views/users/index.html.erb
<%= render partial: 'users/shared/header' %>
<div class="flex flex-col p-4 pt-32 bg-slate-400 min-h-screen">

    <% @users.each do |user| %>
      <div class="bg-white p-4 m-2 rounded-lg flex flex-row justify-between items-center shadow-lg shadow-indigo-500/40">

        <div class="">
          <% if user.photo.present? %>
            <%= image_tag(user.photo, alt: 'User photo', width: 60, height: 60) %>
          <% else %>
            <%= image_tag(ActionController::Base.helpers.asset_path('avatars/13.png'), alt: 'Default photo', width: 60, height: 60) %>
          <% end %>

          <h2 class="font-bold"><%= link_to user.name, user_path(user) %></h2>
        </div>

        <p>Posts: <%= user.posts.count %></p>

      </div>
    <% end %>
  
  
</div>
<%= render partial: 'users/shared/footer' %>

app/views/users/show.html.erb
<%= render partial: 'users/shared/header' %>
<div class="flex flex-col  p-4 pt-32 bg-slate-400 min-h-screen">

  <div class="flex flex-col m-auto items-center">
    <img src="<%= @user.photo %>" alt="User photo" class="w-32 mb-2">
    <div class="flex items-center">
      <h2 class="font-bold"><%= @user.name %></h2>
      <% if user_signed_in? && current_user == @user %>
      <%= link_to "| Edit My Account", edit_user_path(@user), class: 'font-bold ml-2' %>
      <% end %>
    </div>
    <p>Posts: <%= @user.posts.count %></p>
    <p><%= @user.bio %></p>
  </div>

  <% @user.recent_posts.each do |post| %>
    <div class="bg-white p-4 m-2 rounded-lg shadow-lg shadow-indigo-500/40">
      <h3 class="font-bold"><%= link_to post.title, user_post_path(@user, post) %></h3>

      <p><%= post.text.truncate(100) %>... <a href="<%= user_post_path(@user, post) %>">Read more</a></p>
        
      <div class="flex items-center gap-2">
        <%= image_tag("icons/comment", alt: "comment icon", width: 30, height: 30) %>
        <span class="ml-1"><%= post.comments.count %></span>
      
        <%= image_tag("icons/like", alt: "like icon", width: 30, height: 30) %>
        <span class="ml-1"><%= post.likes.count %></span>
      </div>

    </div>

  <% end %>  
  
  <div class="flex flex-row justify-around w-full font-bold mt-4">

    <%= link_to 'See all posts', user_posts_path(@user), class: 'button' %>

    <% if user_signed_in? && current_user == @user %>
      <%= link_to "Create A New Post", new_user_post_path(current_user), class: 'button' %>
    <% end %>

  </div>

    <%= link_to users_path, class: 'm-auto mt-4' do %>
      <%= image_tag("icons/back", alt: "Back icon", width: 35, height: 35) %>
    <% end %>

</div>
<%= render partial: 'users/shared/footer' %>