config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'users#index'
  resources :users, only: [:index, :show, :destroy, :edit, :update] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # api routes

  namespace :api do
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_save :update_posts_counter

  private

  def update_posts_counter
    author.posts_counter = author.posts.count
    author.save
  end
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    def index
      @user = User.find(params[:user_id])
      @posts = @user.posts
      render json: @posts
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.author_id)
    @author = User.find(@post.author_id)
    @new_post = current_user.posts.build if user_signed_in?
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_posts_path(current_user), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @post.comments.destroy_all
    @post.likes.destroy_all
    @post.destroy
    redirect_to user_posts_path(current_user), notice: 'Post was successfully deleted.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<%= render partial: 'users/shared/header' %>
<div class="flex flex-col p-4 pt-32 bg-slate-400 min-h-screen">

  <div class="flex flex-col m-auto items-center">
    <img src="<%= @user.photo %>" alt="User photo", class="w-32">
    <h2 class="font-bold"><%= @user.name %></h2>
    <p>Posts: <%= @user.posts.count %></p>
  </div>
 

  <% @posts.each do |post| %>
    <div class="bg-white p-4 m-2 rounded-lg shadow-lg shadow-indigo-500/40">
      <h2 class="font-bold"><%= link_to post.title, user_post_path(@user, post) %></h2>
      <p><%= post.text %></p>
      <div class="flex items-center gap-2">
        <%= image_tag("icons/comment", alt: "comment icon", width: 30, height: 30) %>
        <span class="ml-1"><%= post.comments.count %></span>
      
        <%= image_tag("icons/like", alt: "like icon", width: 30, height: 30) %>
        <span class="ml-1"><%= post.likes.count %></span>
      </div>
    </div>
  <% end %>

  <%= link_to user_path(current_user), class: 'm-auto mt-4' do %>
    <%= image_tag("icons/back", alt: "Back icon", width: 35, height: 35) %>
  <% end %>

</div>
<%= render partial: 'users/shared/footer' %>

app/views/posts/new.html.erb
<%= render partial: 'users/shared/header' %>
<div class="flex flex-col  p-4 pt-32 bg-slate-400 min-h-screen">
  <div class="bg-white p-4 mt-8 rounded-lg flex flex-col shadow-lg shadow-indigo-500/40 max-w-lg m-auto mt-3">
    <h2 class="font-bold text-lg m-auto">Create a New Post</h2>

    <%= form_with(model: [@user, @post], local: true, html: { class: 'm-4 flex flex-col gap-2' }) do |form| %>
      
        <%= form.text_field :title, placeholder: "Title", class: 'border-indigo-500/100 w-full rounded-lg' %>
      
        <%= form.text_area :text, placeholder: "Write Something...", rows: 5, class: 'border-slate-400 w-full rounded-lg' %>
      
        <%= form.submit "Create Post", class: 'bg-slate-600 hover:bg-slate-700 text-white p-2 rounded-lg font-bold' %>
      
    <% end %>
  </div>
  <%= link_to user_path(current_user), class: 'm-auto mt-4' do %>
    <%= image_tag("icons/back", alt: "Back icon", width: 35, height: 35) %>
  <% end %>
 
</div>
<%= render partial: 'users/shared/footer' %>

app/views/posts/show.html.erb
<%= render partial: 'users/shared/header' %>
<div class="flex flex-col  p-4 pt-32 bg-slate-400 min-h-screen">
  <div class="flex flex-col bg-white p-4 m-2 rounded-lg shadow-lg shadow-indigo-500/40">

    <div class="flex flex-row justify-between m-2">
      <h2 class="font-bold text.lg">Post #<%= @post.id %> by <%= link_to @post.author.name, user_path(@post.author) %></h2>
      <%= form_with(url: user_post_likes_path(@author, @post), method: :post, local: true) do |form| %>
        <%= form.hidden_field :author_id, value: current_user.id %>
        <%= form.button type: "submit", class: "flex items-center", style: "background: none; border: none;" do %>
          <%= image_tag("icons/like.svg", alt: "Like icon", class: "w-6 h-6 mr-1") %>
        <% end %>
      <% end %>
      
    </div>

    <p class="m-2"><%= @post.text %></p>

    <div class="flex items-center gap-2 m-2">
      <%= image_tag("icons/comment", alt: "comment icon", width: 30, height: 30) %>
      <span class="ml-1"><%= @post.comments.count %></span>
      
      <%= image_tag("icons/like", alt: "like icon", width: 30, height: 30) %>
      <span class="ml-1"><%= @post.likes.count %></span>
    </div>

   

    <% @post.comments.each do |comment| %>

      <div class="rounded-lg bg-slate-200 border-none p-2 flex flex-col m-2 gap-2">
        <strong><%= comment.author.name %>:</strong> <%= comment.text %>
        <% if can? :destroy, comment %>
        <%= button_to "/users/#{@user.id}/posts/#{comment.post.id}/comments/#{comment.id}", method: :delete, data: { confirm: 'Are you sure?' } do %>
          <%= image_tag("icons/delete", alt: "Delete icon", width: 20, height: 20) %>
        <% end %>

        <% end %>
      </div>
    
    <% end %>

    <%= form_with(model: [ @post, @post.comments.build ], url: user_post_comments_path(@post.author, @post), local: true, html: { class: 'm-4 flex flex-col gap-2' }) do |form| %>
      <%= form.hidden_field :author_id, value: current_user.id %>
      <%= form.text_area :text, placeholder: "Leave a comment...", rows: 5, class: 'rounded-lg bg-slate-200 border-none' %>
      <%= form.submit "Add Comment", class: 'bg-slate-600 hover:bg-slate-700 text-white p-2 rounded-lg font-bold' %>
    <% end %>
  </div>    
      
    <% if can? :destroy, @post %>
    <%= button_to 'Delete Post', "/users/#{@user.id}/posts/#{@post.id}", method: :delete, data: { confirm: 'Are you sure?' }, class: 'bg-slate-200 hover:bg-slate-300 text-black p-2 rounded-lg font-bold m-2' %>
    <% end %>
  
<%= link_to user_path(current_user), class: 'm-auto mt-4' do %>
  <%= image_tag("icons/back", alt: "Back icon", width: 35, height: 35) %>
<% end %>

</div>
<%= render partial: 'users/shared/footer' %>